### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by JadonKane** [simon-wh/PAYDAY-2-BeardLib-Editor#1]
When I try to download the mod, it asks for a password.

**Comment by LBLuffy** [comment]
You are probably talking about the pdmod, you need to install it using Bundle Modder http://lastbullet.net/mydownloads.php?action=view_down&did=197

**Comment by JadonKane** [comment]
How do I download the mod with Bundle Modder? On all the tutorials on YouTube, they're downloading files completely different from the files in this mod.

**Comment by LBLuffy** [comment]
First the zip file you downloaded in lastbullet has a folder named BeardLib-Editor and it has to be dropped in the **mods** folder(located in your payday 2 directory) so that the folder named BeardLib-Editor is inside your **mods** folder.
and second the addon which is the pdmod that you probably got from here https://www.dropbox.com/s/dp3x8mqfebprx9v/BeardLib-Editor.pdmod?dl=0 has to be **Installed** with bundle modder you don't need to extract the .pdmod just install it using bundle modder.

**Comment by JadonKane** [comment]
Thanks for the help!
