### ISSUE TITLE
Crash on changing script of an element

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib-Editor#42]
https://pastebin.com/5uVMGvvX
Always crash when I change script of any element... Do I am doing something wrong?
Even when I create new map, soo It's not a map faulth...

**Comment by Luffyyy** [comment]
Can't happen when you create a new map you need to update the mod manually(beardlib also)
the auto updates are broken atm sadly.

but issue should be fixed in new version of beardlib and editor, basically if you have two mission scripts with the same name it breaks, last updates of editor prevent that, also it happens with the new maps because the issue was in the templates and I updated them a while ago.
